repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.9
        args: [--line-length=100]  # Adjust line length

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
                - flake8-type-checking

  # - repo: local
  #   hooks:
  #     - id: testing
  #       name: run pytest
  #       entry: pytest
  #       language: system
  #       files: ^tests/.*\.py$
  #       always_run: true
